In [1]:
#numpy called as arrays
import numpy as np

In [2]:
l=["sudh",1,2,3,4]
type(l)

list

In [3]:
np.array(l)

array(['sudh', '1', '2', '3', '4'], dtype='<U11')

In [4]:
type(np.array(l))

numpy.ndarray

In [5]:
a1=np.array([3,4,5,6,3.0])

In [6]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [7]:
a[1][1]

4

In [8]:
a1

array([3., 4., 5., 6., 3.])

In [9]:
a1[1]

4.0

In [10]:
a2=np.array([1,2,3,4],ndmin=4)
a2

array([[[[1, 2, 3, 4]]]])

In [11]:
a2[0][0][0][0]

1

In [12]:
#converts inputs to any dimentsion array
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [13]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [14]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [15]:
a=[1,2,3,4,5]
np.asarray(a)

array([1, 2, 3, 4, 5])

In [16]:
#as it is array
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [17]:
#array to matrix
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [18]:
#(3,3) is matrix dimention
np.fromfunction(lambda i , j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [19]:
#dtype is use to keep output in integer
np.fromfunction(lambda i,j:i*j,(4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [20]:
np.mat(np.fromfunction(lambda i,j:i*j,(4,4)))

matrix([[0., 0., 0., 0.],
        [0., 1., 2., 3.],
        [0., 2., 4., 6.],
        [0., 3., 6., 9.]])

In [21]:
#3D array
np.fromfunction(lambda i,j,z:i*j*z,(3,3,2),dtype=int)

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]]])

In [22]:
#4D array
np.fromfunction(lambda i,j,z,p:i*j*z*p,(4,3,3,2),dtype=int)

array([[[[ 0,  0],
         [ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  0],
         [ 0,  0]]],


       [[[ 0,  0],
         [ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  1],
         [ 0,  2]],

        [[ 0,  0],
         [ 0,  2],
         [ 0,  4]]],


       [[[ 0,  0],
         [ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  2],
         [ 0,  4]],

        [[ 0,  0],
         [ 0,  4],
         [ 0,  8]]],


       [[[ 0,  0],
         [ 0,  0],
         [ 0,  0]],

        [[ 0,  0],
         [ 0,  3],
         [ 0,  6]],

        [[ 0,  0],
         [ 0,  6],
         [ 0, 12]]]])

In [23]:
a=np.fromfunction(lambda i,j,z:i*j*z,(4,3,2),dtype=int)
a

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [24]:
#if we have 20 elements we should give comination of 20 elements in any  dimenstion
#can shape into any number of dimention
a.reshape(5,4)

ValueError: cannot reshape array of size 24 into shape (5,4)

In [25]:
a.reshape(2,2,5)

ValueError: cannot reshape array of size 24 into shape (2,2,5)

In [26]:
a.reshape(2,-1)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4, 0, 0, 0, 3, 0, 6]])

In [27]:
a.ndim

3

In [28]:
a.size

24

In [29]:
a.shape

(4, 3, 2)

In [30]:
a.dtype

dtype('int32')

In [31]:
#we cannot convert 3D array into dataframe
#as dtat frame is 2D
import pandas as pd
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [ ]:
a=np.fromfunction(lambda i,j:i*j,(400,300),dtype=int)
a

In [ ]:
pd.DataFrame(a)

In [32]:
np.random.rand(100,4)

array([[0.31004043, 0.42133196, 0.8009448 , 0.38364941],
       [0.08562313, 0.45337647, 0.86047431, 0.38860559],
       [0.92190611, 0.90129804, 0.9054931 , 0.7134437 ],
       [0.49744166, 0.19113432, 0.0779826 , 0.09808641],
       [0.27701854, 0.65216688, 0.48508579, 0.58043871],
       [0.62460357, 0.81714115, 0.62381249, 0.58802343],
       [0.17307145, 0.29426523, 0.12584548, 0.53652301],
       [0.22126464, 0.07071145, 0.88597089, 0.4056147 ],
       [0.13962658, 0.78715742, 0.62894881, 0.5730845 ],
       [0.70117105, 0.71604344, 0.13345265, 0.37680297],
       [0.0383642 , 0.98768406, 0.53421041, 0.64920569],
       [0.57223127, 0.21415401, 0.32804975, 0.16605899],
       [0.55551614, 0.22044623, 0.52128771, 0.32721285],
       [0.89265983, 0.50603116, 0.15216546, 0.90837328],
       [0.46120161, 0.96004495, 0.6488413 , 0.87052762],
       [0.99784608, 0.43568624, 0.25116891, 0.49496268],
       [0.98458078, 0.81795336, 0.93264276, 0.79164016],
       [0.15091555, 0.77154019,

In [33]:
np.random.randint(4,50)

7

In [34]:
#normal distributed numbers mean=0,SD=1
a=np.random.randn(4,5)

In [35]:
pd.DataFrame(a)

0         1         2         3         4
0 -1.075094 -1.400885 -0.011837  1.063755 -1.021107
1  0.181120 -0.163935 -1.646428 -2.090370  0.343551
2 -1.598295  0.086412 -2.016754  0.048739  0.010811
3  0.452609  0.829506 -0.847744 -0.198040 -0.417424

In [36]:
#range only works for integer
list(range(4,10,2))

[4, 6, 8]

In [37]:
#range only works for integer&float(decimal)
a1=np.arange(4,10,.2)
a1

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [38]:
a1[1:4]

array([4.2, 4.4, 4.6])

In [39]:
arr=np.random.rand(4,5)
arr

array([[0.7218442 , 0.76376276, 0.03607422, 0.90638597, 0.55986483],
       [0.19412221, 0.3273193 , 0.58020536, 0.4308775 , 0.57716624],
       [0.97641465, 0.25942109, 0.31001191, 0.09801385, 0.0481654 ],
       [0.69677345, 0.97785418, 0.17063821, 0.82744112, 0.23193895]])

In [40]:
arr[arr>.5]

array([0.7218442 , 0.76376276, 0.90638597, 0.55986483, 0.58020536,
       0.57716624, 0.97641465, 0.69677345, 0.97785418, 0.82744112])

In [41]:
arr[(1,2),(2)]

array([0.58020536, 0.31001191])

In [42]:
arr=np.random.rand(8,5)
arr

array([[0.30907166, 0.89272851, 0.38100668, 0.47941178, 0.53596795],
       [0.49996833, 0.11392329, 0.67843279, 0.70971127, 0.18066094],
       [0.0858335 , 0.22593622, 0.86568797, 0.61372551, 0.47122908],
       [0.58969753, 0.69771053, 0.99495924, 0.60677173, 0.84381824],
       [0.22485736, 0.92504656, 0.31210997, 0.48365456, 0.02792863],
       [0.70911734, 0.87179021, 0.95532044, 0.68992205, 0.63128738],
       [0.62863254, 0.4756597 , 0.81272195, 0.44048402, 0.22783024],
       [0.50491141, 0.1760515 , 0.66911708, 0.98116996, 0.0647006 ]])

In [43]:
arr[1:8,0:3]

array([[0.49996833, 0.11392329, 0.67843279],
       [0.0858335 , 0.22593622, 0.86568797],
       [0.58969753, 0.69771053, 0.99495924],
       [0.22485736, 0.92504656, 0.31210997],
       [0.70911734, 0.87179021, 0.95532044],
       [0.62863254, 0.4756597 , 0.81272195],
       [0.50491141, 0.1760515 , 0.66911708]])

In [44]:
a2=arr[1:8,[0,1,2]]
a2

array([[0.49996833, 0.11392329, 0.67843279],
       [0.0858335 , 0.22593622, 0.86568797],
       [0.58969753, 0.69771053, 0.99495924],
       [0.22485736, 0.92504656, 0.31210997],
       [0.70911734, 0.87179021, 0.95532044],
       [0.62863254, 0.4756597 , 0.81272195],
       [0.50491141, 0.1760515 , 0.66911708]])

In [45]:
a2[0][0]=100
a2

array([[1.00000000e+02, 1.13923295e-01, 6.78432791e-01],
       [8.58335000e-02, 2.25936219e-01, 8.65687968e-01],
       [5.89697532e-01, 6.97710526e-01, 9.94959244e-01],
       [2.24857358e-01, 9.25046559e-01, 3.12109965e-01],
       [7.09117343e-01, 8.71790206e-01, 9.55320435e-01],
       [6.28632542e-01, 4.75659697e-01, 8.12721952e-01],
       [5.04911414e-01, 1.76051501e-01, 6.69117076e-01]])

In [46]:
a=np.array([[1,2],[3,4]])
b=np.array([[2,3],[4,5]])

In [47]:
a

array([[1, 2],
       [3, 4]])

In [48]:
b

array([[2, 3],
       [4, 5]])

In [49]:
a*b

array([[ 2,  6],
       [12, 20]])

In [50]:
# '@' is matrix multiplication function
m=a@b
m

array([[10, 13],
       [22, 29]])

In [51]:
m/0

C:\Users\harsh\AppData\Local\Temp\ipykernel_10800\3791875896.py:1: RuntimeWarning: divide by zero encountered in true_divide
  m/0


array([[inf, inf],
       [inf, inf]])

In [52]:
l=[21,2,3,4,54]
np.asarray(l)

array([21,  2,  3,  4, 54])

In [53]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [54]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [55]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [56]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [57]:
np.ones((3,6,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [58]:
#5 is the vector.vector as both magnitude and dimension
#if we perform same kind of operation with all elements present in my space is called broadcasting
#below is broadcasting operation
5+np.ones((3,6,2))

array([[[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]]])

In [59]:
np.empty((4,5))
np.empty((4,5,2))

array([[[0.30907166, 0.89272851],
        [0.38100668, 0.47941178],
        [0.53596795, 0.49996833],
        [0.11392329, 0.67843279],
        [0.70971127, 0.18066094]],

       [[0.0858335 , 0.22593622],
        [0.86568797, 0.61372551],
        [0.47122908, 0.58969753],
        [0.69771053, 0.99495924],
        [0.60677173, 0.84381824]],

       [[0.22485736, 0.92504656],
        [0.31210997, 0.48365456],
        [0.02792863, 0.70911734],
        [0.87179021, 0.95532044],
        [0.68992205, 0.63128738]],

       [[0.62863254, 0.4756597 ],
        [0.81272195, 0.44048402],
        [0.22783024, 0.50491141],
        [0.1760515 , 0.66911708],
        [0.98116996, 0.0647006 ]]])

In [60]:
#btw 2-6 20 number is generated
#50 is default number
#end point eliminate last value 6
np.linspace(2,6,20,endpoint=False).reshape(5,4)

array([[2. , 2.2, 2.4, 2.6],
       [2.8, 3. , 3.2, 3.4],
       [3.6, 3.8, 4. , 4.2],
       [4.4, 4.6, 4.8, 5. ],
       [5.2, 5.4, 5.6, 5.8]])

In [61]:
#.2 is step size
np.linspace(2,6,20,endpoint=False,retstep=True)

(array([2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4,
        4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8]),
 0.2)

In [62]:
np.logspace(2,4,10,base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [63]:
np.linspace(2,4,10)

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [64]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
a.max(axis=1)

array([ 3,  7, 11, 15])

In [66]:
a.max(axis=0)

array([12, 13, 14, 15])

In [67]:
10+a

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [68]:
a/0

C:\Users\harsh\AppData\Local\Temp\ipykernel_10800\4102073204.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0
C:\Users\harsh\AppData\Local\Temp\ipykernel_10800\4102073204.py:1: RuntimeWarning: invalid value encountered in true_divide
  a/0


array([[nan, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [69]:
a**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]], dtype=int32)

In [70]:
pow(a,3)

array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331],
       [1728, 2197, 2744, 3375]], dtype=int32)

In [71]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
b=np.array([2,3,1,2])
b

array([2, 3, 1, 2])

In [73]:
a+b

array([[ 2,  4,  3,  5],
       [ 6,  8,  7,  9],
       [10, 12, 11, 13],
       [14, 16, 15, 17]])

In [74]:
a+10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [75]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [76]:
np.exp(a)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]])

In [77]:
np.log10(a)

C:\Users\harsh\AppData\Local\Temp\ipykernel_10800\547625357.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(a)


array([[      -inf, 0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125, 0.84509804],
       [0.90308999, 0.95424251, 1.        , 1.04139269],
       [1.07918125, 1.11394335, 1.14612804, 1.17609126]])

In [78]:
x=np.array([1,2,3])

In [79]:
#solve copy(allot to same inedx position)
y=x

In [80]:
y

array([1, 2, 3])

In [81]:
#deep copy
z=np.copy(x)
z

array([1, 2, 3])

In [82]:
x[0]=100

In [83]:
y

array([100,   2,   3])

In [84]:
z

array([1, 2, 3])

In [85]:
id(z)

3047256051856

In [86]:
id(z[1])

3047255862576

In [87]:
id(x)

3047256052912

In [88]:
id(x[0])

3047255862736

In [89]:
id(y)

3047256052912

In [90]:
id(y[0])

3047255862864

In [91]:
su=np.array([567,345])
df=su

In [92]:
id(su)

3047256053104

In [93]:
id(df)

3047256053104

In [94]:
id(su[1])==id(df[0])

True

In [98]:
id(su[1])==id(df[1])

True

In [103]:
xt=np.array([34,67,89])

In [107]:
id(xt[0])==id(su[0])

True

In [109]:
c='sudh'
id(c)==id(su[0])

False